name: 'docker-compose build & push to registry'
description: 'docker-compose build , push and push to registry'
inputs:
  service-name:
    description: 'docker-compose build service'
    required: true
  repository:
    description: 'ecr repository name'
    required: true
  tag:
    description: 'ecr repository tag'
    required: true
  working-directory:
    description: 'docker-compose execute directory'
    required: false
    default: '.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.service-name }}
    - ${{ inputs.repository }}
    - ${{ inputs.tag }}
    - ${{ inputs.working-directory }}

